force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>A tournament is a series of matches played until a winner is declared.</description>
    <label>Tournament</label>
    <nameField>
        <displayFormat>TN - {000000}</displayFormat>
        <label>Tournament Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Winning_Team__c.field-meta.xml
<CustomField>
    <fullName>Winning_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The winning team of the tournament</description>
    <label>Winning Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournaments Won</relationshipLabel>
    <relationshipName>Tournaments_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tournaments.cls
public without sharing class Tournaments {
    public static List<Tournament> getActiveOrPendingTournaments(Boolean includeOnlyTodays) {
        List<Tournament__c> tournaments = new List<Tournament__c>();
        if(includeOnlyTodays) {
            tournaments = [
                SELECT Id, Status__c, Name, Winning_Team__c
                FROM Tournament__c
                WHERE (Status__c = 'Active' OR Status__c = 'Pending') 
                AND CreatedDate = TODAY
            ];
        } else {
            tournaments = [
                SELECT Id, Status__c, Name, Winning_Team__c
                FROM Tournament__c
                WHERE (Status__c = 'Active' OR Status__c = 'Pending')
            ];
        }

        return Tournament.wrap(tournaments);
    }

    public static Tournament createNewTournament(String status) {
        Tournament__c tn = new Tournament__c(Status__c = status);
        INSERT tn;
        tn = [SELECT Id, Name, Status__c FROM Tournament__c WHERE Id = :tn.Id];
        return Tournament.wrap(tn);
    }
}