force-app/main/default/objects/Player_In_Team__c/Player_In_Team__c.object-meta.xml
<CustomObject>
    <description>A sports player in a team</description>
    <label>Player In Team</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player In Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_In_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team that player is in</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players In Team</relationshipLabel>
    <relationshipName>Players_In_Team</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Teams consist of multiple players</description>
    <label>Team</label>
    <nameField>
        <displayFormat>TM - {000000}</displayFormat>
        <label>Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <description>Give a nice name to you team, for eg: Wind Smashers</description>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Team.cls
public class Team {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String teamNumber;
    @AuraEnabled
    public List<Player> playersInTeam;

    public Team(String id, String teamNumber) {
        this.id = id;
        this.teamNumber = teamNumber;
    }

    public Team setTeamName(String teamName) {
        this.name = teamName;
        return this;
    }

    public Team setPlayersInTeam(List<Player> players) {
        this.playersInTeam = players;
        return this;
    }

    public static List<Team> wrap(List<Team__c> teams) {
        List<Team> teamsWrapped = new List<Team>();
        for(Team__c t : teams) {
            teamsWrapped.add(
                new Team(t.Id, t.Name)
                .setTeamName(t.Team_Name__c)
                .setPlayersInTeam(Player.wrap(t.Players_In_Team__r))
            );
        }
        return teamsWrapped;
    }
}