force-app/main/default/objects/Player_In_Team__c/Player_In_Team__c.object-meta.xml
<CustomObject>
    <description>A sports player in a team</description>
    <label>Player In Team</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player In Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_In_Team__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <description>The person who will play in the team</description>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player In Teams</relationshipLabel>
    <relationshipName>Player_In_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_In_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team that player is in</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players In Team</relationshipLabel>
    <relationshipName>Players_In_Team</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Teams consist of multiple players</description>
    <label>Team</label>
    <nameField>
        <displayFormat>TM - {000000}</displayFormat>
        <label>Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Player.cls
public class Player {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String playerName;
    @AuraEnabled
    public String teamId;
    @AuraEnabled
    public String contactId;

    public Player(String id, String name, String playerName, String contactId, String teamId) {
        this.id = id;
        this.name = name;
        this.playerName = playerName;
        this.contactId = contactId;
        this.teamId = teamId;
    }

    public static List<Player> wrap(List<Player_In_Team__c> playersInTeam) {
        List<Player> playersInTeamWrapped = new List<Player>();
        for(Player_In_Team__c pit : playersInTeam) {
            playersInTeamWrapped.add(
                new Player(pit.Id, pit.Name, pit.Person__r?.Name, pit.Person__c, pit.Team__c)
            );
        }
        return playersInTeamWrapped;
    }
}