force-app/main/default/objects/Player_In_Team__c/Player_In_Team__c.object-meta.xml
<CustomObject>
    <description>A sports player in a team</description>
    <label>Player In Team</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player In Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_In_Team__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <description>The person who will play in the team</description>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player In Teams</relationshipLabel>
    <relationshipName>Player_In_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_In_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>The team that player is in</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players In Team</relationshipLabel>
    <relationshipName>Players_In_Team</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Teams consist of multiple players</description>
    <label>Team</label>
    <nameField>
        <displayFormat>TM - {000000}</displayFormat>
        <label>Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <description>Give a nice name to you team, for eg: Wind Smashers</description>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TeamSelector.cls
public without sharing class TeamSelector {
    public static List<Team__c> retrieveTeamsByContactIds(List<Id> contactIds) {
        return [
            SELECT Id, Name, Team_Name__c,
            (SELECT Id, Name, Team__c, Person__c, Person__r.Name FROM Players_In_Team__r)
            FROM Team__c
            WHERE Id IN (SELECT Team__c FROM Player_In_Team__c WHERE Person__c IN :contactIds AND Team__c != null)
        ];
    }

    public static List<Team__c> retrieveTeams(List<Id> teamIds) {
        return [
            SELECT Id, Name, Team_Name__c,
            (SELECT Id, Name, Team__c, Person__c, Person__r.Name FROM Players_In_Team__r)
            FROM Team__c
            WHERE Id IN :teamIds
        ];
    }
}