force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>A match is played between 2 or more teams</description>
    <label>Match</label>
    <nameField>
        <displayFormat>M - {0000000}</displayFormat>
        <label>Match Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The tournament that this match is related to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Teams consist of multiple players</description>
    <label>Team</label>
    <nameField>
        <displayFormat>TM - {000000}</displayFormat>
        <label>Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>A tournament is a series of matches played until a winner is declared.</description>
    <label>Tournament</label>
    <nameField>
        <displayFormat>TN - {000000}</displayFormat>
        <label>Tournament Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchBuilder.cls
public without sharing class MatchBuilder {
    public static Integer teamsPerMatch = 2;

    public static List<Match> buildMatches(Tournament tn, List<Team> teams) {
        Integer numberOfTeams = teams.size();
        Integer matchImperfectionNumber = Math.mod(numberOfTeams, teamsPerMatch);
        Integer numOfMatchesToCreate = getNumberOfMatchesToCreate(numberOfTeams, matchImperfectionNumber);
        List<Match> matches = createMatches(tn, numOfMatchesToCreate);
        CollectionUtil.randomizeList(matches);
        addTeamsToMatches(matches, teams);
        return matches;
    }

    private static void addTeamsToMatches(List<Match> matches, List<Team> teams) {
        Integer numberOfTeams = teams.size();
        List<Team_In_Match__c> teamInMatchesToCreate = new List<Team_In_Match__c>();
        Integer index = 0;
        for(Match m : matches) {
            m.setTeamsPerMatch();
            Integer teamsAddedToThisMatch = 0;
            while(index < numberOfTeams && teamsAddedToThisMatch < teamsPerMatch) {
                m.addTeam(teams[index]);
                teamInMatchesToCreate.add(new Team_In_Match__c(
                    Match__c = m.id,
                    Team__c = teams[index].id
                ));
                index++;
                teamsAddedToThisMatch++;
            }
        }
        INSERT teamInMatchesToCreate;
    }

    private static Integer getNumberOfMatchesToCreate(Integer teamSize, Integer matchImperfectionNumber) {
        return matchImperfectionNumber == 0 ? 
        teamSize / teamsPerMatch : 
        ((teamSize - matchImperfectionNumber) / teamsPerMatch) + 1;
    }

    private static List<Match> createMatches(Tournament tn, Integer numOfMatchesToCreate) {
        List<Match__c> matchesToCreate = new List<Match__c>();
        for(Integer i = 0; i < numOfMatchesToCreate; i++) {
            matchesToCreate.add(new Match__c(Tournament__c = tn.id));
        }
        INSERT matchesToCreate;
        List<Match__c> matchesInserted = [SELECT Id, Name, Tournament__c FROM Match__c WHERE Id IN :matchesToCreate];
        return Match.wrap(matchesInserted, tn);
    }


}